server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/core/ {
        proxy_pass http://hypoc-face-core:8000/;
        proxy_set_header Host $host;
    }

    location /api/router/ {
        proxy_pass http://hypoc-face-router:8001/;
        proxy_set_header Host $host;
    }
}
